BlogApp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from users import views as user_views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import BlogSitemap, StaticViewSitemap

sitemaps = {
    "posts": BlogSitemap,
    "staticviews": StaticViewSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html', redirect_authenticated_user=True), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('profile/', user_views.profile, name= 'profile'),
    path('sitemap.xml', sitemap, {"sitemaps": sitemaps}, name="sitemap"),
    path('', include('users.urls')),
    path('', include('newsapp.urls')),
    path(r'^tinymce/', include('tinymce.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import include, path
from . import views
from .views import PostListView, PostDetailView, PostCreateView, PostUpdateView, PostDeleteView, UserPostListView, SearchListView, CommentDeleteView

app_name = 'blog'
urlpatterns = [
    path('', views.landing, name='landing'),
    path('blog/', PostListView.as_view(), name= 'blog-home'),
    path('user/<str:username>', UserPostListView.as_view(), name= 'user-posts'),
    path('blog/post/<slug:slug>/<int:pk>/', PostDetailView.as_view(), name= 'post_detail'),
    path('blog/post/new/', PostCreateView.as_view(), name='post_create'),
    path('blog/post/<slug:slug>/<int:pk>/update/', PostUpdateView.as_view(), name='post_update'),
    path('blog/post/<slug:slug>/<int:pk>/delete/', PostDeleteView.as_view(), name='post_delete'),
    path('blog/comment/<int:pk>/delete/', CommentDeleteView.as_view(), name='comment_delete'),
    path('about/', views.about, name = 'blog-about'),
    path('services/', views.services, name='services'),
    path('contact/', views.contact, name = 'blog-contact'),
    path('search/', SearchListView.as_view(), name='search'),
    path('projects/', views.projects, name='blog-projects'),

]

# <app>/<model>_<viewtype>.html

newsapp/urls.py
from django.urls import include, path
from . import views

app_name = "newsapp"

urlpatterns = [
    path('engadget/', views.news, name = "news_home"),
    path('bbc/', views.bbc, name = "bbc"),
    path('wsj/', views.tws, name = "wsj"),
    path('corona/', views.corona, name = "corona"),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User
# Create your models here.

class Tag(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

class Post(models.Model):
    CATEGORY = (('CCTV Cameras', 'CCTV Cameras'), ('Politics','Politics'), ('History', 'History'), ('General News','General News'), ('Technology', 'Technology'), ('Gaming', 'Gaming'))
    title = models.CharField(max_length=255, blank=True)
    content = models.TextField(blank=True)
    date_posted = models.DateTimeField(default=timezone.now)
    #we didn't use timezone.now() because we just want to get the value
    images = models.ImageField(blank=True, upload_to='post_pics')
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.CharField(max_length=255, null=True, choices=CATEGORY)
    slug = models.SlugField(max_length=255, null=True)
    #on_delete is used when we want to delete content of deleted user
    tag = models.ManyToManyField(Tag)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("blog:post_detail", kwargs={'slug': self.slug, 'pk': self.pk})

    """def get_absolute_url(self):
        return reverse('blog:post_detail', kwargs={'pk': self.pk})
    """
    def save(self, *args, **kwargs):  # new
        if not self.slug:
            self.slug = slugify(self.title)
        return super().save(*args, **kwargs)

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80, blank=True)
    email = models.EmailField(blank=True)
    body = models.TextField(blank=True)
    comm_images = models.ImageField(blank=True, upload_to='comment_images')
    created_on = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=False)

    class Meta:
        ordering = ['created_on']

    def __str__(self):
        return 'Comment {} by {}'.format(self.body, self.name)

blog/forms.py
from .models import Comment
from django import forms

class CommentForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    email = forms.EmailField()
    class Meta:
        model = Comment
        fields = '__all__'
        widgets = {
            'post': forms.HiddenInput(),
            'active': forms.HiddenInput()
        }

class SearchForm(forms.Form):
    query = forms.CharField(max_length = 100)

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic.edit import FormMixin, ModelFormMixin
from django.http import HttpResponse
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, FormView
from django.core.mail import send_mail
from django.contrib import messages
# Create your views here.
from .models import Post, Comment
from django.http import HttpResponseRedirect
import requests
from .forms import CommentForm, SearchForm
from django.contrib.auth.models import User
from django.urls import reverse, reverse_lazy
from django.db.models import Q
import random
from django import template
import requests

def home(request):
    context = {
        'posts': Post.objects.all()
    }
    return render(request, 'blog/home.html', context)

def landing(request):
    context = {
        'posts': Post.objects.all()
    }

    return render(request, 'blog/landing.html', context)

def services(request):
    return render(request, 'blog/services.html')

def projects(request):
    return render(request, 'blog/projects.html')

class PostListView(ListView):
    model = Post
    template_name = 'blog/home.html'
    context_object_name = 'posts'
    ordering = ['-date_posted']
    paginate_by = 5

class SearchListView(ListView):
    template_name = 'blog/home.html'
    model = Post
    context_object_name = "posts"
    paginate_by = 5

    def get_queryset(self):
        query = self.request.GET.get('q')

        if query:
            object_list = self.model.objects.filter(title__icontains=query)
        else:
            object_list = self.model.objects.none()
        return object_list

class PostDetailView(FormMixin, DetailView):
    model = Post
    template_name = "blog/post_detail.html"
    form_class = CommentForm

    def get_success_url(self):
        return reverse("blog:post_detail", args=[self.kwargs['slug'], self.kwargs['pk']])


    def get_context_data(self, **kwargs):
        pk = self.kwargs.get("pk")
        context = super(PostDetailView, self).get_context_data(**kwargs)
        context['comment'] = Comment.objects.filter(post=self.kwargs['pk']).order_by('-created_on')
        context['form'] = CommentForm(initial={'active': True, 'post': self.kwargs['pk']})
        context['times'] = range(1, 8)
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()

        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        form.save()
        return super(PostDetailView, self).form_valid(form)

class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['title', 'content', 'images', 'category', 'tag']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    fields = ['title', 'content', 'images']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    success_url = '/blog/'

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


class CommentDeleteView(LoginRequiredMixin, DeleteView):
    model = Comment

    def get_success_url(self):
        return reverse('blog:post_detail', kwargs={'slug': self.object.post.slug, 'pk': self.object.post.pk})

class UserPostListView(ListView):
    model = Post
    template_name = 'blog/user_posts.html'
    context_object_name = 'posts'
    paginate_by = 5

    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        return Post.objects.filter(author=user).order_by('-date_posted')

def about(request):
    return render(request, 'blog/about.html', {'title': 'About Us'})

def contact(request):

    if request.method == "POST":
        message_name = request.POST['message-name']
        message_email = request.POST['message-email']
        message = request.POST['message']

        send_mail(
            'Inquiry: ' + " " + message_name + " - " + message_email,
             message,
             message_email,
             ['clickstartcctv@gmail.com'],
        )
        #python -m smtpd -n -c DebuggingServer localhost:1025
        return render(request, 'blog/contactus.html', {'message_name': message_name})

    else:
        return render(request, 'blog/contactus.html', {})

blog/templates/base/contactbase.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="google-site-verification" content="Emks-YLoot3OEzodAeA8ozXMkzPs6dmyx9qSco8ELz0"/>
    <meta name="keywords" content="Clickstart, Click Start, clickstartCCTV, clickstartcctv, clickstart cctv, cctv, CCTV, cctv camera istallation, cctv installation, installation, camera installation, cctv installation near laguna, cctv camera near laguna, cctv installation around laguna, service, cctv for sale, Laguna, laguna, security camera, security, cameras, camera, ncr, NCR, Metro Manila, cctv near metro manila, cctv around manila, camera business, cctv camera, cctv cameras, around Laguna, Installation, CCTV around Laguna, DVR, dvr, nvr, bullet camera, hikvision, Hikvision, dahua, zik, biometric system, system, biometrics, attendance, time and attendance, santa rosa laguna, cabuyao, calamba">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Inconsolata" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Zilla+Slab" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Signika&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Teko" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=B612" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Muli" rel="stylesheet">
    <link rel="shortcut icon" href="{% static 'blog/images/favicon.ico' %}">
    <script src="https://cdn.tiny.cloud/1/4uo76d4wgycsi3tr3xqkyrpzlm401b9t5op28iiewjvm8d3w/tinymce/5/tinymce.min.js"
            referrerpolicy="origin"></script>
    <script>tinymce.init({selector: "textarea:not(.mceNoEditor)", plugins: "image"});</script>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-172978446-1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];

        function gtag() {
            dataLayer.push(arguments);
        }

        gtag('js', new Date());

        gtag('config', 'UA-172978446-1');
    </script>
    <script async defer crossorigin="anonymous"
            src="https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v7.0&appId=607953923186783&autoLogAppEvents=1"
            nonce="w1WVOZ4l"></script>

    <!--{% if title %}
        <title>Clickstart CCTV| {{ title }}</title>

    {% else %}
        <title>Clickstart CCTV</title>

    {% endif %}-->

    <title>Clickstart CCTV | {% block title %}{% endblock %}</title>

    <link rel="stylesheet" href="{% static 'blog/contactstyle.css' %}">

</head>
<!--<body style = 'background: #ffffff; background-image: url("{% static 'blog/images/walking-girl.png' %}"); background-repeat: no-repeat; background-position: bottom right; background-size: 50% 50%'>-->
<body style='background: #ffffff;'>
<header class="site-header">
    <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
            <a class="navbar-brand mr-4" style="font-family: 'Signika', sans-serif; font-size: 25px;" href="/"><img
                    src="{% static 'blog/images/click_icon150x150.png' %}"
                    style="width: 50px; height: 50px; margin-right: 10px; ">CLICKSTART CCTV</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"
                    aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggle">
                <div class="navbar-nav mr-auto">
                    <a class="nav-item nav-link" href="{% url 'blog:landing' %}">Home</a>
                    <a class="nav-item nav-link" href="{% url 'blog:blog-home' %}">Blog</a>

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Newsroom
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{% url 'newsapp:news_home' %}">Engadget</a>
                            <a class="dropdown-item" href="{% url 'newsapp:bbc' %}">BBC</a>
                            <a class="dropdown-item" href="{% url 'newsapp:wsj' %}">The Wall Street Journal</a>
                            <a class="dropdown-item" href="{% url 'newsapp:corona' %}">Coronavirus Latest News</a>
                        </div>
                    </li>

                    <a class="nav-item nav-link" href="{% url 'blog:blog-contact' %}">Contact Us</a>



                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            About
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{% url 'blog:blog-about' %}">Company Information</a>
                            <a class="dropdown-item" href="{% url 'blog:blog-projects' %}">Our Projects</a>
                            <a class="dropdown-item" href="{% url 'blog:services' %}">Services</a>
                            <!--<a class="dropdown-item" href="{% url 'newsapp:wsj' %}">The Wall Street Journal</a>-->
                        </div>
                    </li>
                </div>
                <!-- Navbar Right Side -->
                <div class="navbar-nav">
                    {% if user.is_authenticated %}
                        <a class="nav-item nav-link" href="{% url 'blog:post_create' %}">New Post</a>
                        <a class="nav-item nav-link" href="{% url 'profile' %}">Profile</a>
                        <a class="nav-item nav-link" href="{% url 'logout' %}">Log Out</a>
                    {% else %}
                        <a class="nav-item nav-link" href="{% url 'login' %}">Log In</a>
                    {% endif %}
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <form class="form-inline ml-auto" method="GET" action="{% url 'blog:search' %}">
                            <div class="md-form my-0 ml-2">
                                <input class="form-control" type='text' name='q' value='{{ request.GET.q }}'>
                            </div>
                            <button class="todo-button"
                                    style="padding: 0.5rem; margin:0; border: none; background: transparent;"
                                    type="submit">
                                <i class="fa fa-search"></i>
                            </button>
                        </form>
                    </div>

                </div>
            </div>
        </div>
    </nav>
</header>

{% block content %} {% endblock %}

<!----------- Footer ------------>
<footer class="footer-bs">
    <div class="row">
        <div class="col-md-3 footer-brand animated fadeInLeft text-center">
            <img id="footerimg" src="{% static 'blog/images/click_icon150x150.png' %}">
            <p>Clickstart CCTV's mission is to provide the people with security to the highest degree through video
                surveillance solutions. With this clear-cut objective in mind, the dedication, grit, and hardwork of our
                staff will ensure that we will always deliver on our promise.</p>
            <p>© 2020 Clickstart CCTV, All rights reserved</p>
        </div>
        <div class="col-md-4 footer-nav animated fadeInUp">
            <h4>Menu —</h4>
            <div class="col-md-6">
                <ul class="pages">
                    <li><a href="{% url 'blog:blog-about' %}">About Us</a></li>
                    <li><a href="{% url 'blog:blog-contact' %}">Contact Us</a></li>
                    <!--<li><a href="#">Explores</a></li>
                    <li><a href="#">Science</a></li>
                    <li><a href="#">Advice</a></li>-->
                </ul>
            </div>
            <!--<div class="col-md-6">
                <ul class="list">
                    <li><a href="#">About Us</a></li>
                    <li><a href="#">Contacts</a></li>
                    <li><a href="#">Terms & Condition</a></li>
                    <li><a href="#">Privacy Policy</a></li>
                </ul>
            </div>-->
        </div>
        <div class="col-md-2 footer-social animated fadeInDown">
            <h4>Follow Us</h4>
            <ul>
                <li><a target='_blank' href="https://www.facebook.com/clickstartcctv/"><i
                        class="fa fa-facebook-square mr-2" aria-hidden="true"></i>Facebook</a></li>
                <li><a target='_blank' href="https://twitter.com/clickstartcctv"><i class="fa fa-twitter mr-2"
                                                                                    aria-hidden="true"></i>Twitter</a>
                </li>
                <li><a target='_blank' href="https://www.instagram.com/clickstartcctv/"><i class="fa fa-instagram mr-2"
                                                                                           aria-hidden="true"></i>Instagram</a>
                </li>
                <li><a target='_blank' href="https://www.youtube.com/channel/UCBPEHyFfB6RXDetde5EU6Vw"><i
                        class="fa fa-youtube mr-2" aria-hidden="true"></i>Youtube</a></li>
            </ul>
        </div>


        <!--<div class="col-md-3 footer-ns animated fadeInRight">
            <h4>Newsletter</h4>
            <p>A rover wearing a fuzzy suit doesn’t alarm the real penguins</p>
            <p>
            <div class="input-group">
                <input type="text" class="form-control" placeholder="Search for...">
                <span class="input-group-btn">
                        <button class="btn btn-default" type="button"><span class="fa fa-envelope"></span></button>
                      </span>
            </div>
            </p>
        </div>-->
    </div>
</footer>
<section style="text-align:center; margin:10px auto;"><p>Copyright © 2020 Clickstart CCTV. All Rights Reserved.</p>
</section>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>

</body>
</html>