BlogApp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from users import views as user_views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import BlogSitemap, StaticViewSitemap

sitemaps = {
    "posts": BlogSitemap,
    "staticviews": StaticViewSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html', redirect_authenticated_user=True), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('profile/', user_views.profile, name= 'profile'),
    path('sitemap.xml', sitemap, {"sitemaps": sitemaps}, name="sitemap"),
    path('', include('users.urls')),
    path('', include('newsapp.urls')),
    path(r'^tinymce/', include('tinymce.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import include, path
from . import views
from .views import PostListView, PostDetailView, PostCreateView, PostUpdateView, PostDeleteView, UserPostListView, SearchListView, CommentDeleteView

app_name = 'blog'
urlpatterns = [
    path('', views.landing, name='landing'),
    path('blog/', PostListView.as_view(), name= 'blog-home'),
    path('user/<str:username>', UserPostListView.as_view(), name= 'user-posts'),
    path('blog/post/<slug:slug>/<int:pk>/', PostDetailView.as_view(), name= 'post_detail'),
    path('blog/post/new/', PostCreateView.as_view(), name='post_create'),
    path('blog/post/<slug:slug>/<int:pk>/update/', PostUpdateView.as_view(), name='post_update'),
    path('blog/post/<slug:slug>/<int:pk>/delete/', PostDeleteView.as_view(), name='post_delete'),
    path('blog/comment/<int:pk>/delete/', CommentDeleteView.as_view(), name='comment_delete'),
    path('about/', views.about, name = 'blog-about'),
    path('services/', views.services, name='services'),
    path('contact/', views.contact, name = 'blog-contact'),
    path('search/', SearchListView.as_view(), name='search'),
    path('projects/', views.projects, name='blog-projects'),

]

# <app>/<model>_<viewtype>.html

newsapp/urls.py
from django.urls import include, path
from . import views

app_name = "newsapp"

urlpatterns = [
    path('engadget/', views.news, name = "news_home"),
    path('bbc/', views.bbc, name = "bbc"),
    path('wsj/', views.tws, name = "wsj"),
    path('corona/', views.corona, name = "corona"),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User
# Create your models here.

class Tag(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

class Post(models.Model):
    CATEGORY = (('CCTV Cameras', 'CCTV Cameras'), ('Politics','Politics'), ('History', 'History'), ('General News','General News'), ('Technology', 'Technology'), ('Gaming', 'Gaming'))
    title = models.CharField(max_length=255, blank=True)
    content = models.TextField(blank=True)
    date_posted = models.DateTimeField(default=timezone.now)
    #we didn't use timezone.now() because we just want to get the value
    images = models.ImageField(blank=True, upload_to='post_pics')
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.CharField(max_length=255, null=True, choices=CATEGORY)
    slug = models.SlugField(max_length=255, null=True)
    #on_delete is used when we want to delete content of deleted user
    tag = models.ManyToManyField(Tag)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("blog:post_detail", kwargs={'slug': self.slug, 'pk': self.pk})

    """def get_absolute_url(self):
        return reverse('blog:post_detail', kwargs={'pk': self.pk})
    """
    def save(self, *args, **kwargs):  # new
        if not self.slug:
            self.slug = slugify(self.title)
        return super().save(*args, **kwargs)

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80, blank=True)
    email = models.EmailField(blank=True)
    body = models.TextField(blank=True)
    comm_images = models.ImageField(blank=True, upload_to='comment_images')
    created_on = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=False)

    class Meta:
        ordering = ['created_on']

    def __str__(self):
        return 'Comment {} by {}'.format(self.body, self.name)

blog/forms.py
from .models import Comment
from django import forms

class CommentForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    email = forms.EmailField()
    class Meta:
        model = Comment
        fields = '__all__'
        widgets = {
            'post': forms.HiddenInput(),
            'active': forms.HiddenInput()
        }

class SearchForm(forms.Form):
    query = forms.CharField(max_length = 100)

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic.edit import FormMixin, ModelFormMixin
from django.http import HttpResponse
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, FormView
from django.core.mail import send_mail
from django.contrib import messages
# Create your views here.
from .models import Post, Comment
from django.http import HttpResponseRedirect
import requests
from .forms import CommentForm, SearchForm
from django.contrib.auth.models import User
from django.urls import reverse, reverse_lazy
from django.db.models import Q
import random
from django import template
import requests

def home(request):
    context = {
        'posts': Post.objects.all()
    }
    return render(request, 'blog/home.html', context)

def landing(request):
    context = {
        'posts': Post.objects.all()
    }

    return render(request, 'blog/landing.html', context)

def services(request):
    return render(request, 'blog/services.html')

def projects(request):
    return render(request, 'blog/projects.html')

class PostListView(ListView):
    model = Post
    template_name = 'blog/home.html'
    context_object_name = 'posts'
    ordering = ['-date_posted']
    paginate_by = 5

class SearchListView(ListView):
    template_name = 'blog/home.html'
    model = Post
    context_object_name = "posts"
    paginate_by = 5

    def get_queryset(self):
        query = self.request.GET.get('q')

        if query:
            object_list = self.model.objects.filter(title__icontains=query)
        else:
            object_list = self.model.objects.none()
        return object_list

class PostDetailView(FormMixin, DetailView):
    model = Post
    template_name = "blog/post_detail.html"
    form_class = CommentForm

    def get_success_url(self):
        return reverse("blog:post_detail", args=[self.kwargs['slug'], self.kwargs['pk']])


    def get_context_data(self, **kwargs):
        pk = self.kwargs.get("pk")
        context = super(PostDetailView, self).get_context_data(**kwargs)
        context['comment'] = Comment.objects.filter(post=self.kwargs['pk']).order_by('-created_on')
        context['form'] = CommentForm(initial={'active': True, 'post': self.kwargs['pk']})
        context['times'] = range(1, 8)
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()

        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        form.save()
        return super(PostDetailView, self).form_valid(form)

class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['title', 'content', 'images', 'category', 'tag']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    fields = ['title', 'content', 'images']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    success_url = '/blog/'

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


class CommentDeleteView(LoginRequiredMixin, DeleteView):
    model = Comment

    def get_success_url(self):
        return reverse('blog:post_detail', kwargs={'slug': self.object.post.slug, 'pk': self.object.post.pk})

class UserPostListView(ListView):
    model = Post
    template_name = 'blog/user_posts.html'
    context_object_name = 'posts'
    paginate_by = 5

    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        return Post.objects.filter(author=user).order_by('-date_posted')

def about(request):
    return render(request, 'blog/about.html', {'title': 'About Us'})

def contact(request):

    if request.method == "POST":
        message_name = request.POST['message-name']
        message_email = request.POST['message-email']
        message = request.POST['message']

        send_mail(
            'Inquiry: ' + " " + message_name + " - " + message_email,
             message,
             message_email,
             ['clickstartcctv@gmail.com'],
        )
        #python -m smtpd -n -c DebuggingServer localhost:1025
        return render(request, 'blog/contactus.html', {'message_name': message_name})

    else:
        return render(request, 'blog/contactus.html', {})

blog/templates/blog/comment_confirm_delete.html
{% extends "base/base.html" %}
{% block content %}
    <div class="content-section" style="margin-top:25px;">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class = "border-bottom mb-4">Delete Post</legend>
                <h2>Are you sure you want to delete the post "{{ comment.name }}"</h2>
            </fieldset>
            <div class="form-group">
                <button class ="btn btn-outline-danger" type="submit">Yes, Delete</button>
                <a class ="btn btn-outline-secondary" href="{% url 'blog:post_detail' slug=comment.post.slug pk=comment.post.id %}">Cancel</a>
            </div>
        </form>
    </div>
{% endblock content %}

blog/templates/blog/contactus.html
{% extends 'base/contactbase.html' %}
{% load static %}

{% block title %} Contact Us {% endblock %}
{% block content %}
    {% if message_name %}
        <div class="alert alert-success" role="alert">
            Thanks {{ message_name }}! We'll respond to you shortly.
        </div>
    {% endif %}

    <div class="mapcontainer">
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3866.3209840504037!2d121.09387551577191!3d14.292773388375622!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3397d83a23b4c475%3A0xfbafe06ef6aff9d4!2sClickstart%20CCTV!5e0!3m2!1sfil!2sph!4v1595241834628!5m2!1sfil!2sph"
                width="100%" height="100%" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false"
                tabindex="0"></iframe>
    </div>



    <div class="container-fluid" id="contactform">
        <div class="row justify-content-center" id="wholerow">

                <div class="col-md-5" id="container1">
                    <h2>Contact Information</h2>

                    <div class="row" id="contactrows">
                        <img style="margin-right: 2px;" class="contact-img" src= {% static 'blog/images/contactus/call.png' %}>
                        <ul class="text-left">
                            <li>Sun: 0932-171-2155</li>
                            <li>Globe: 0995-077-6502</li>
                            <li>Smart: 0939-191-7600</li>
                        </ul>

                    </div>

                    <div class="row" id="contactrows">
                        <img class="contact-img" src= {% static 'blog/images/contactus/sydney-opera-house.png' %}>
                        <h6 style="font-size: 14px;" class="mt-2">#998 JB Village2, Brgy, Balibago, <br>Santa Rosa, 4026 Laguna</h6>
                    </div>

                    <div class="row" id="contactrows">
                        <img class="contact-img" src= {% static 'blog/images/contactus/mail.png' %}>
                        <h6 class="mt-2">clickstartcctv@gmail.com</h6>
                    </div>

                    <div class="row" id="contactrows">
                        <img class="contact-img" src= {% static 'blog/images/facebook.png' %}>
                        <h6 class="mt-2">facebook.com/clickstartcctv</h6>
                    </div>
                </div>




            <div class="col-md-5" id="contactas">
                <h2 style="font-family: 'Signika', sans-serif;">Get in Touch!</h2>
                <h5>You may send us your inquiries by writing a message below, and we'll get back to you right away. You
                    may
                    also send us a call or text at <b>0932-171-2155</b></h5>
                <hr>
                <form action="{% url 'blog:blog-contact' %}" method="POST" class="theform">
                    {% csrf_token %}
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label for="yourname">Your Name</label>
                            <input type="text" class="form-control" id="yourname" name="message-name" placeholder=""
                                   required>
                        </div>
                        <div class="form-group col-md-6">
                            <label for="youremail">Your E-mail</label>
                            <input type="email" class="form-control" id="youremail" name="message-email" placeholder=""
                                   required>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="inputAddress">Your Message</label>
                        <textarea style="height: 100px;" class="mceNoEditor form-control" id="mainmessage"
                                  name="message"
                                  placeholder=""></textarea>
                    </div>
                    <button type="submit" class="btn btn-primary">Send</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/landing.html
<!DOCTYPE html>
<html lang="en">
{% extends 'base/landingbase.html' %}
{% load static %}
{% block content %}
    <div id="secondcon2" class="container-fluid">
        <div id="conrow" class="row justify-content-center">
            <div class="col-md-5">
                <div id ="services1" class="card">
                    <div id="services" class="card-body">
                        <h1 id="catcher" style = "font-size: 6vh;">I want <span id="thetyped"></span></h1>
                        <h5 id="below">As technology and business methods advance more than ever,
                            security becomes a
                            necessity for everybody and everything.<br><br>
                            We at Clickstart CCTV makes it easier for you to ensure that safety is accessible.</h5>
                        <a id="but" class="btn btn-primary btn-lg" href="{% url 'blog:blog-contact' %}" style="color:white;">Get Started</a>
                    </div>
                </div>
            </div>
            <div class="col-md-5">
                <div id ="services2" class="card">
                    <div id="services" class="card-body">
                        <img id="sec" src="{% static 'blog/images/landing/security.png' %}">
                    </div>
                </div>
            </div>
        </div>
    </div>


    <div class="container text-center">
        <h1 id="getQuote" style="margin-top: 60px;" class="text-center">Get a Quote!</h1>
        <h5 id="below" class="text-center">Contact us by pressing the middle button below, and get a customized
            quotation from us depending on your requirements.</h5>
        <div class="row justify-content-center">
            <a id="but" class="btn btn-info btn-lg text-center" href="{% url 'blog:blog-home' %}"
               style="color:white;">Our Blog</a>
            <a id="but" class="btn btn-primary btn-lg text-center" href="{% url 'blog:blog-contact' %}"
               style="color:white;">Contact Us</a>
            <a id="but" class="btn btn-danger btn-lg text-center" href="{% url 'newsapp:news_home' %}"
               style="color:white;">The Newsroom</a>
        </div>
    </div>

    <div class="container text-center" style="margin-top: 150px; margin-bottom: 100px;">
        <div class="row justify-content-center">
            <img id="products1" src="{% static 'blog/images/landing/hikvision.png' %}">
            <img id="products" src="{% static 'blog/images/landing/dahua.png' %}">
            <img id="products" src="{% static 'blog/images/landing/zkteco.png' %}">
            <img id="products1" src="{% static 'blog/images/landing/ubiquiti.png' %}">
        </div>
    </div>

     <h1 id="about" class="text-center" id="about">About Us</h1>

    <h3 id ="about" class="text-center" id="about2">Clickstart CCTV and Computer Installation Services</h3>
    <div class="container" id="img-container">
        <img id="logo" src="/media/profile_pics/click_icon150x150.png"><p id="info-company">
        <strong>Clickstart CCTV Company</strong> was founded by Mr. Allan Palma Cruz in October 2019.
            As a newly-established company, Clickstart uses this as its pride and drive in having the unwavering determination to provide the best services possible.
            We specialize in the supply, design, maintenance, and installation of video surveillance systems with the best interest of the customers’ individual needs in mind.
            Equipped with in-depth understanding of the latest technology, we are committed in helping our customers in finding the most comprehensive solutions.
        </p>
    </div>
    <div class="container" id="mission">
        <h2 class="text-center" id="about">Our Mission and Vision</h2>

        <p id ="vision" class= "text-center">
            Clickstart CCTV's mission is to provide the people with security to the highest degree through video surveillance solutions.
            With this clear-cut objective in mind, the dedication, grit, and hardwork of our staff will ensure that we will always deliver on our promise.</p>
    </div>


    <div style="margin-top: 100px;"class="container-fluid text-center">
        <h1 id="catcher" class="text-center">This is how we work.</h1>
        <h5 id="below" class="text-center">Security Redefined.</h5>
        <div class="row justify-content-center">
            <div class="col-sm-4">
                <div class="card">
                    <div id="services" class="card-body">
                        <img id="serviceimage" src="{% static 'blog/images/services/customized.png' %}">
                        <h2 id="servicetext" class="text-center">Customized Requirements</h2>
                        <p id="servicesmall" class="text-center">We are more than eager to meet the client's every need
                            and requirement,
                            from
                            method of installation and schedule to materials.</p>
                    </div>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="card">
                    <div id="services" class="card-body">
                        <img id="serviceimage" src="{% static 'blog/images/services/delivery.png' %}">
                        <h2 id="servicetext">Quality Materials</h2>
                        <p id="servicesmall">The materials used for installation of cameras are handpicked to ensure
                            efficiency and quality.</p>
                    </div>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="card">
                    <div id="services" class="card-body">
                        <img id="serviceimage" src="{% static 'blog/images/services/highquality.png' %}">
                        <h2 id="servicetext">Outstanding Service</h2>
                        <p id="servicesmall">Every step we take is scrutinized so that we can achieve the desired
                            results
                            of
                            the client. </p>
                    </div>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="card">
                    <div id="services" class="card-body">
                        <img id="serviceimage" src="{% static 'blog/images/services/highvalue.png' %}">
                        <h2 id="servicetext" class="text-center">Value for Money</h2>
                        <p id="servicesmall" class="text-center">We make sure that every penny you spend is matched to
                            the best and suitable
                            CCTV
                            cameras and services that we offer.</p>
                    </div>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="card">
                    <div id="services" class="card-body">
                        <img id="serviceimage" src="{% static 'blog/images/services/support.png' %}">
                        <h2 id="servicetext">Long-Term Warranty</h2>
                        <p id="servicesmall">We provide one-year warranty to make sure that you're covered in every
                            problem
                            that might arise.</p>
                    </div>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="card">
                    <div id="services" class="card-body">
                        <img id="serviceimage" src="{% static 'blog/images/services/cloud.png' %}">
                        <h2 id="servicetext">Anytime, Anywhere</h2>
                        <p id="servicesmall">The CCTV cameras are your eyes and ears, and you can see and hear them in a
                            simple touch on a viewing app in your smartphone! </p>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <div class="container text-center" style="margin-bottom: 80px;">
        <h1 id="catcher">Follow Us!</h1>
        <div class="row justify-content-center">
            <a href="https://www.facebook.com/clickstartcctv/"><img id="socials"
                                                                    src="{% static 'blog/images/facebook.png' %}"></a>
            <a href="https://www.instagram.com/clickstartcctv/"><img id ="socials" src="{% static 'blog/images/instagram.png' %}"></a>
            <a href="https://twitter.com/clickstartcctv"><img id ="socials" src="{% static 'blog/images/twitter.png' %}"></a>
            <a href="https://www.youtube.com/channel/UCBPEHyFfB6RXDetde5EU6Vw"><img id ="socials" style="margin-right: 0px;" src="{% static 'blog/images/youtube.png' %}"></a>
        </div>
    </div>

    <div class="container-fluid text-center">
        <h1 id="catcher" class="text-center">Our Blog</h1>
        <h5 style="margin-bottom: 50px;"id="below" class="text-center">A collection of information that might help you. Take a look.</h5>

        <div class="row justify-content-center">

            {% for post in posts|slice:"3" %}
                <div class="card1" style="width: 20rem; margin-bottom: 25px;">
                    <div class="card-body">
                        <h5 style ="font-family: 'Signika', sans-serif;"class="card-title">{{ post.title }}</h5>
                        <a target="_blank" href="{% url 'blog:post_detail' slug=post.slug pk=post.id %}" class="btn btn-info">Read More</a>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

    <script>
        var options = {
            strings: ['Security.', 'Monitoring.', 'Safety.'],
            typeSpeed: 65,
            backSpeed: 65,
            smartBackspace: true,
            loop: true
        };

        var typed = new Typed('#thetyped', options);
    </script>

{% endblock %}
</html>

blog/templates/blog/post_detail.html
<!DOCTYPE html>
{% extends "base/base.html" %}
{% load crispy_forms_tags %}
{% load el_pagination_tags %}
{% load social_share %}
{% load static %}

{% block title %}{{ object.title }}{% endblock %}

{% block content %}
    <article class="media content-section mb-4 mt-4">
        <div class="media-body">
            <div class="article-metadata mb-4">
                <img class='rounded-circle article-img' alt="ClickstartCCTV Profile Picture" src="{{ object.author.profile.image.url }}">
                <a class="mr-2" href="{% url 'blog:user-posts' object.author.username %}">{{ object.author }}</a>
                <small class="text-muted">{{ object.date_posted|date:"F d, Y" }}</small>
                {% if object.author == user %}
                    <a class="btn btn-secondary btn-sm mt-1 mb-1"
                       href="{% url 'blog:post_update' slug=object.slug pk=object.id %}">Update</a>
                    <a class="btn btn-danger btn-sm mt-1 mb-1"
                       href="{% url 'blog:post_delete' slug=object.slug pk=object.id %}">Delete</a>
                {% endif %}
            </div>
            <div class="container">
                <h2 class="article-title mb-4">{{ object.title }}</h2>
                <i class="fa fa-list-alt" aria-hidden="true"></i> Category: {{ object.category }}<br>
                <i class="fa fa-tag" aria-hidden="true"></i> Tags:
                {% for tags in object.tag.all %}
                    <i>{{ tags.name }}</i>
                    {{ forloop.last|yesno:",&#44;"|safe }}
                {% empty %}
                    None
                {% endfor %}
                {% if object.images %}
                    <img src="{{ object.images.url }}" alt="" style='height: 100%; width: 100%; object-fit: contain'>
                {% endif %}
                <p class="article-content">{{ object.content|safe }}</p>
                <br>
                <div style="margin-bottom:8px;"><strong>Liked the content? You may share it to your favourite sites.</strong></div>
                <div class="row" style="margin-left:3px;">
                    {% post_to_facebook object.title %}
                    {% post_to_twitter object.title %}
                </div>
            </div>

        </div>
    </article>

    <h4 class="mt-4 mb-4">{{ comment.count }} Comments for "{{ object.title }}":</h4>

    {% if object.comments %}
        {% paginate 5 comment %}
        {% for coms in comment %}
            <article class="media content-section mb-4 ml-2" style="border-color:white">
                <img class='rounded-circle article-img' src="/media/profile_pics/sylvanas.jpg" alt="Clickstart CCTV Commenter Image">

                <div class="media-body">
                    <div class="mb-2">
                        <b><a class="mr-2">{{ coms.name }}</a></b>
                        <small class="text-muted">{{ coms.created_on }}</small>
                        {% if user.is_authenticated %}
                            <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'blog:comment_delete' coms.id %}">Delete</a>
                        {% endif %}
                    </div>
                    <b><p class="article-content mt-6">{{ coms.body|safe }}</p></b>
                    {% if coms.comm_images %}
                        <img id="commentimg" src="{{ coms.comm_images.url }}" alt="">
                    {% endif %}

                </div>

            </article>
        {% endfor %}
        {% get_pages %}
        <ul class="pagination mb-4 mt-4">
            {% if pages.paginated %}
                <li class="page-item">
                    <a class="page-link" href="{{ pages.first.path }}" aria-label="First">
                        <span aria-hidden="true">&lt;&lt;</span>
                        <span class="sr-only">First</span>
                    </a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="{{ pages.previous.path }}" aria-label="Previous">
                        <span aria-hidden="true">&lt;</span>
                        <span class="sr-only">Previous</span>
                    </a>
                </li>
                {% for page in pages %}
                    {% if page == None %}
                        <li class="page-item disabled">
                            <a class="page-link" href="#" aria-label="...">
                                <span aria-hidden="true">...</span>
                                <span class="sr-only">...</span>
                            </a>
                        </li>
                    {% else %}
                        <li class="page-item {% if page.is_current %} active {% endif %}">
                            <a class="page-link" href="{{ page.path }}" aria-label="Page {{ page.number }}">
                                <span aria-hidden="true">{{ page.label|safe }}</span>
                                <span class="sr-only">Page {{ page.number }}</span>
                            </a>
                        </li>
                    {% endif %}
                {% endfor %}
                <li class="page-item">
                    <a class="page-link" href="{{ pages.next.path }}" aria-label="Next">
                        <span aria-hidden="true">&gt;</span>
                        <span class="sr-only">Next</span>
                    </a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="{{ pages.last.path }}" aria-label="Last">
                        <span aria-hidden="true">&gt;&gt;</span>
                        <span class="sr-only">Last</span>
                    </a>
                </li>
            {% endif %}
        </ul>

    {% endif %}


        <div class="content-section">
            <h2 class="mt-4 mb-4">Write a Comment!</h2>
            <form enctype="multipart/form-data" action="" method="POST">
                {% csrf_token %}
                {{ form|crispy }}
                <button class="btn btn-outline-info" type="submit">Submit</button>
            </form>
        </div>


{% endblock content %}